export const RegisterTexts = {
    en: {
      title: "Register Now",
      btn: "Register",
      name: "User name",
      email: "Email address",
      password: "Password",
      confirmPassword: "Confirm password",
      phone: "Phone number",
      success: "Congratulations!",
      requiredName: "Name is required",
      minName: "Name must be at least 3 characters",
      maxName: "Name must be at most 16 characters",
      invalidEmail: "Invalid email format",
      requiredEmail: "Email is required",
      requiredPhone: "Phone number is required",
      invalidPhone: "Invalid phone number",
      requiredPassword: "Password is required",
      minPassword: "Password must be at least 6 characters",
      maxPassword: "Password must be at most 12 characters",
      confirmRequired: "Please confirm your password",
      passwordNotMatch: "Passwords do not match",
      account: "Already have an account ?",
    },
    ar: {
      title: "أنشئ حساب",
      btn: "سجل",
      name: "اسم المستخدم",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      phone: "رقم الهاتف",
      success: "تهانينا!",
      requiredName: "الاسم مطلوب",
      minName: "الاسم يجب أن يكون 3 أحرف على الأقل",
      maxName: "الاسم يجب ألا يتجاوز 16 حرفًا",
      invalidEmail: "صيغة البريد غير صحيحة",
      requiredEmail: "البريد مطلوب",
      requiredPhone: "رقم الهاتف مطلوب",
      invalidPhone: "رقم الهاتف غير صحيح",
      requiredPassword: "كلمة المرور مطلوبة",
      minPassword: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
      maxPassword: "كلمة المرور يجب ألا تتجاوز 12 حرفًا",
      confirmRequired: "يجب تأكيد كلمة المرور",
      passwordNotMatch: "كلمات المرور غير متطابقة",
      account: "هل لديك حساب بالفعل ؟" ,

    }
  }
  